name: CI
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: status-im/nimbus-common-workflow/.github/workflows/common.yml@d87d946fd3dee34f9eca5496fbb5adf359d378e8
    with:
      test-command: |
        env NIMLANG=c nimble test
        env NIMLANG=cpp nimble test
